# Generated by Django 6.0 on 2026-01-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note1',
            new_name='Note',
        ),
    ]
